version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: protractor-cucumber-framework
    versions:
    - 6.2.1
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 8.0.0
    - 8.0.1
    - 8.0.2
  - dependency-name: cucumber-html-reporter
    versions:
    - 5.3.0
